# account base config

[database]
  [database.master]
    engine = "mysql"
    name = "account"
    user = "root"
    password = "123456"
    host = "127.0.0.1"
    port = 4406
    subFix = "charset=utf8mb4&loc=Local&parseTime=true"
    maxOpenConns = 100

  [[database.slaves]]
    engine = "mysql"
    name = "account"
    user = "root"
    password = "123456"
    host = "127.0.0.1"
    port = 4406
    subFix = "charset=utf8mb4&loc=Local&parseTime=true"
    maxOpenConns = 100

[redis]
  [redis.cache]
    host = "127.0.0.1"
    port = 6379
    db = 0
    password = ""

[auth]
  secretKey = "oHon8zzsF13u2Uyj23S0P2xbtlRmjDIlDMZh7GwCxKRhpjjdUOo3gFtXQ4pT8Dvg" # SHA-256 slat for password generate
